### ISSUE TITLE
"Uncaught TypeError: Cannot read property '1' of null" on test execution

### ISSUE THREAD

**Issue by feserafim** [dp28/minizinc-solver#1]
Hello. I was unable to use "minizinc-solver". It seems there is an error in `src/index.js` file.

This is the error I get when a run the `npm test`:
```bash
Uncaught TypeError: Cannot read property '1' of null
     at parseSolverError (src/index.js:62:55)
     at handleMiniZincError (src/index.js:56:44)
     at src/index.js:50:15
     at src/timed-exec.js:28:16
     at ChildProcess.<anonymous> (src/timed-exec.js:47:5)
     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
npm ERR! Test failed.  See above for more details.
```

Is there any way to make it work?
Greetings.

**Comment by dp28** [comment]
Sorry for the late reply, I've been pretty busy recently. I've just pushed a fix for the particular error you've shown, but it looks like here may be an underlying problem. What OS are you using? The version of MiniZinc this uses is for 64-bit Linux, which may be causing an error. Hopefully, my change should make any underlying errors slightly easier to see.

**Comment by dp28** [comment]
I'm closing this as there hasn't been any activity in two years. If there is still a problem, let me know.
