### ISSUE TITLE
Setting Minizinc Path? 

### ISSUE THREAD

**Issue by optimisercom** [dp28/minizinc-solver#4]
Hi @dp28 @Zlazrak @feserafim @rpapad01 

1. I npm installed it into a MeteorJS project.
2. My server test code as below:

```
var minizincSolver = require("minizinc-solver");
var problem = String('var 0..1: x;solve satisfy;output ["x -> ", show(x)];');
minizincSolver.solve(problem, console.log);
```

My result was:

```
I20190518-18:42:30.869(12)? var 0..1: x;solve satisfy;output ["x -> ", show(x)];
=> Meteor server restarted
I20190518-18:42:31.175(12)? { isMiniZincError: true,
I20190518-18:42:31.177(12)?   type: 'syntax_error',
I20190518-18:42:31.178(12)?   message: 'MiniZinc error: (line ): c error: sh: 1: mzn2fzn: not found\nminizinc: could not invoke mzn2fzn: unknown result code from system command\n' }
```

I think I didn't set the Minizinc location correctly. 
For CLI, it is `export PATH=$PATH:~/MiniZincIDE-2.2.3-bundle-linux/bin/`
I'm not sure how to make it working with MeteorJS.

Do you know what is the issue?
Thanks in advance!!!

**Comment by dp28** [comment]
I've just patched this module so that exporting the `PATH` as you did should work as long as you have minizinc installed. Assuming you run your Meteor server with `npm start`, then you could make minizinc work with on of the following:

```bash
export PATH=$PATH:~/MiniZincIDE-2.2.3-bundle-linux/bin
npm start
```

or

```bash
PATH=$PATH:~/MiniZincIDE-2.2.3-bundle-linux/bin npm start
```

**Comment by optimisercom** [comment]
Hi @dp28 

Thanks for your quick reply. 
After that, I have another issue:

````
=> Meteor server restarted
I20190520-22:33:14.822(12)? { isMiniZincError: true,
I20190520-22:33:14.824(12)?   type: 'syntax_error',
I20190520-22:33:14.825(12)?   message: 'MiniZinc error: (line ): c error: minizinc: Unrecognized option or bad format `--num-solutions\'\n' }
````

Do you know what cause that? 
Thanks again!

**Comment by dp28** [comment]
Are you using the same test problem as before? If not, could you please
show your MiniZinc code?

**Comment by optimisercom** [comment]
Hi @dp28 
Yes. It is the same test problem as before:

````
var minizincSolver = require("minizinc-solver");
var problem = String('var 0..1: x;solve satisfy;output ["x -> ", show(x)];');
minizincSolver.solve(problem, console.log);
````

**Comment by dp28** [comment]
I've pushed another change to fix this. The library uses the Gecode solver, which is what the `--num-solutions` is for. The new fix makes sure the Gecode solver is used.

**Comment by optimisercom** [comment]
Hi @dp28 

Thanks again for your help.
No luck here yet.

````
=> Meteor server restarted                                              
I20190521-12:16:36.197(12)? { isMiniZincError: true,
I20190521-12:16:36.200(12)?   type: 'syntax_error',
I20190521-12:16:36.203(12)?   message: 'MiniZinc error: (line ): c error: /home/kaiph/MiniZincIDE-2.2.3-bundle-linux/bin/fzn-gecode: error while loading shared libraries: libQt5PrintSupport.so.5: cannot open shared object file: No such file or directory\n' }
````

I checked 

````
dpkg -s libQt5PrintSupport.so.5 | grep Status
dpkg-query: package 'libqt5printsupport.so.5' is not installed and no information is available
````

and installed

````
sudo apt-get update
sudo apt-get install libqt5printsupport5
````

Next issue:

````
I20190521-12:22:53.650(12)? { isMiniZincError: true,
I20190521-12:22:53.652(12)?   type: 'syntax_error',
I20190521-12:22:53.658(12)?   message: 'MiniZinc error: (line ): c error: /home/kaiph/MiniZincIDE-2.2.3-bundle-linux/bin/fzn-gecode: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.9\' not found (required by /home/kaiph/MiniZincIDE-2.2.3-bundle-linux/bin/fzn-gecode)\n' }
````
I installed

````
sudo apt-get install libqt5gui5
````

Checked

````
dpkg -s libQt5Core.so.5 | grep Status
dpkg-query: package 'libqt5core.so.5' is not installed and no information is available
````

Reinstalled

````
sudo apt install --reinstall libqt5widgets5 libqt5gui5 libqt5dbus5 libqt5network5 libqt5core5a
````

Checked

````
dpkg -s libQt5Core.so.5 | grep Status
dpkg-query: package 'libqt5core.so.5' is not installed and no information is available
````

Still...

````
=> Meteor server restarted                                              
I20190521-12:35:51.611(12)? { isMiniZincError: true,
I20190521-12:35:51.614(12)?   type: 'syntax_error',
I20190521-12:35:51.616(12)?   message: 'MiniZinc error: (line ): c error: /home/kaiph/MiniZincIDE-2.2.3-bundle-linux/bin/fzn-gecode: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.9\' not found (required by /home/kaiph/MiniZincIDE-2.2.3-bundle-linux/bin/fzn-gecode)\n' }
````

Any tips?

**Comment by dp28** [comment]
I'm afraid that this looks like an issue with your MiniZinc installation or
operating system. I don't think that I will be able to debug this as I
cannot reproduce it on my machine.

If you would like to debug further yourself, I think you could try changing
the solver from Gecode. One of the last commits on `master` should be a
good example of how to do this. You should be able to get a list of all
possible solvers using `minizinc --solvers`, assuming it is on your path.

I don't know much about it, but I believe Qt is used for building GUIs, so
I am unsure why it is used in the FlatZinc executable.

**Comment by optimisercom** [comment]
Hi @dp28 

No worry, I guessed it is the Qt version issue... I'm downloading Qt_5.9.8 and see if that works.

````
wget http://download.qt.io/official_releases/qt/5.9/5.9.8/qt-opensource-linux-x64-5.9.8.run 
````

I will update you the progress.
Thanks again for your help ;-)
